spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.41.204:3306/dublincomputer?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password:

mybatis:

  typeAliasesPackage: com.wangdefa.permission_controll.entity,com.wangdefa.permission_controll.framework.security
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  configLocation: classpath:mybatis/framework/mybatis-config.xml